version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - "/mnt/hdd/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
