version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - "/mnt/hdd/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER: "${MYSQL_USER}"
      - MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
